version: '3.8'

services:
  app:
    build: .
    image: meu-php-app
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: minha_db
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
